services:
  - type: web
    name: face-recog-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: gunicorn app:app --timeout 180 --workers 1 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MALLOC_ARENA_MAX
        value: 2
    secrets:
      - file: serviceAccountKey.json 
        name: serviceAccountKey.json
